### ISSUE TITLE
[Feature][Registry] Add ZooKeeper Registry Plugin

### ISSUE THREAD

**Issue by zixi0825** [datavane/datavines#1]
### Search before asking

- [X] I had searched in the [feature](https://github.com/datavines-ops/datavines/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Add ZooKeeper Registry Plugin

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by jfly0902** [comment]
I am willing to submit a PR

**Comment by zixi0825** [comment]
done
