### ISSUE TITLE
[Bug][UI] 前端编译报错

### ISSUE THREAD

**Issue by Allen-zy** [datavane/datavines#158]
### Search before asking

- [X] I had searched in the [feature](https://github.com/datavines-ops/datavines/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.12.1:install-node-and-npm (install node and npm) on project datavines-ui: Could not download Node.js: Could not download https://nodejs.org/dist/v18.0.0/node-v18.0.0-linux-x64.tar.gz: 网络不可达 (connect failed) -> [Help 1]
编译时报错，必须在本机挂梯子才能下载node-v18.0.0-linux-x64.tar.gz
希望提供编译好的版本食用

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by zixi0825** [comment]
本周应该可以提供编译好的tar包

**Comment by leslielee58** [comment]
> 本周应该可以提供编译好的tar包

哪里下载呀

**Comment by yinlice** [comment]
ui编译不通过.

**Comment by yinlice** [comment]
> 本周应该可以提供编译好的tar包

可以提供下吗?
