### ISSUE TITLE
[Feature][作业管理功能] 数据质量作业

### ISSUE THREAD

**Issue by bahskzs** [datavane/datavines#161]
### Search before asking

- [X] I had searched in the [feature](https://github.com/datavines-ops/datavines/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

![image](https://github.com/datavane/datavines/assets/64458230/dd8f57e1-b3d3-44fe-b47b-0686de6d23f1)
非空校验的时候正常应该是不需要期望值吧？这个地方有点怪怪的

### Usage Scenario

数据质量检查

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by zixi0825** [comment]
The actual value of non empty verification here is the number of non empty rows in the statistical field. You can choose the expected value as the number of table rows, and the verification result is configured as actual value/expected value * 100%>99, so the result is true

If you don't need to use the expected value due, you can choose any one or fill in a number with a fixed value, and the expected value won't be used. Later, we can add the type of expected value without for checking without expected value.

--------------------------------------------------------------------------------------------------------------------------------------

这里的非空校验实际值是统计字段非空的行数，你可以选择期望值为表行数，校验结果配置为 实际值/期望值 *100% > 99，那么如果结果是大于99，结果就为真。
如果你不需要用到期望值，你可以随便选一个，或者选择固定值填个数字，期望值就用不到，后面我们可以增加 无 的期望值类型，用于无需期望值的检查。

**Comment by bahskzs** [comment]
非常感谢。我明白啦。期待后续发展

发件人: ***@***.***>
发送时间: 2023年7月10日 10:38
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [datavane/datavines] [Feature][作业管理功能] 数据质量作业 (Issue #161)


The actual value of non empty verification here is the number of non empty rows in the statistical field. You can choose the expected value as the number of table rows, and the verification result is configured as actual value/expected value * 100%>99, so the result is true

If you don't need to use the expected value due, you can choose any one or fill in a number with a fixed value, and the expected value won't be used. Later, we can add the type of expected value without for checking without expected value.


这里的非空校验实际值是统计字段非空的行数，你可以选择期望值为表行数，校验结果配置为 实际值/期望值 *100% > 99，那么如果结果是大于99，结果就为真。
如果你不需要用到期望值，你可以随便选一个，或者选择固定值填个数字，期望值就用不到，后面我们可以增加 无 的期望值类型，用于无需期望值的检查。

―
