### ISSUE TITLE
[Bug] 启动失败  java.lang.NoSuchFieldError: IS_SECURITY_ENABLED

### ISSUE THREAD

**Issue by hsoftxl** [datavane/datavines#164]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datavines-ops/datavines/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

Ubuntu 20.04,  按https://datavane.github.io/datavines-website/docs/get-started/deploy-from-source 步骤，在启动时报错
 java.lang.NoSuchFieldError: IS_SECURITY_ENABLED

删除了libs包中的jsp-2.1-6.1.14.jar 后，启动正常。

### DataVines Version

最新版一直有

### DataVines Config

```conf
与配置无关
```

### Running Command

```shell
正常启动
```

### Error Exception

```log
java.lang.NoSuchFieldError: IS_SECURITY_ENABLED
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by zixi0825** [comment]
The problem has been fixed.
