### ISSUE TITLE
运行成功后没有任何结果

### ISSUE THREAD

**Issue by codeBoy777** [datavane/datavines#173]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datavines-ops/datavines/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

spark引擎运行成功，但是没有任何结果信息，也没异常报错，没有趋势图

### DataVines Version

dev分支编译的

### DataVines Config

```conf
字段空值检查、固定值10，阈值10则失败
```

### Running Command

```shell
客户端界面直接运行的
```

### Error Exception

```log
无异常信息
```

### Engine Type

spark

### Java Version

8

### Screenshots

![image](https://github.com/datavane/datavines/assets/50009087/ad638ff6-9911-4392-85b4-03b7f7c9c2cf)
![image](https://github.com/datavane/datavines/assets/50009087/abd87d84-d94a-43a6-a86a-57eba81fa9ef)
![image](https://github.com/datavane/datavines/assets/50009087/a7e88e2b-e173-450a-9ce6-1e66fbb0b017)

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by zixi0825** [comment]
点击结果旁边的日志按钮，看一下日志，应该是没执行成功的

**Comment by zixi0825** [comment]
使用Spark引擎需要把服务部署在能提交spark-submit的节点上，并且配置好Yarn的配置信息（有用到yarn的话）

**Comment by codeBoy777** [comment]
> 使用Spark引擎需要把服务部署在能提交spark-submit的节点上，并且配置好Yarn的配置信息（有用到yarn的话）

这里说配置好yarn的配置信息，是指datavines需要集成yarn还是spark与yarn的集成，spark与yarn环境是正常的
![image](https://github.com/datavane/datavines/assets/50009087/13001fc2-fbf9-45b3-8fe3-97d9a6b23e99)

**Comment by zixi0825** [comment]
common.properties 文件中的配置
yarn.mode=standalone
yarn.application.status.address=http://%s:%s/ws/v1/cluster/apps/%s
yarn.resource.manager.http.address.port=8088

可参考https://datavane.github.io/datavines-website/docs/get-started/deploy-from-source

**Comment by codeBoy777** [comment]
> 

我这里配置过了，下面的星号就是我配置的ip地址，我们是yarn环境的，所以没有用standalone
yarn.mode=ha
yarn.application.status.address=http://%s:%s/ws/v1/cluster/apps/%s
yarn.resource.manager.http.address.port=8088
yarn.resource.manager.ha.ids=*****

**Comment by zixi0825** [comment]
你到Yarn的那个日志页面里面看一下有没有报错信息，理论上执行成功以后会把结果数据写回datavines的，如果没有结果的话就有可能是Spark任务执行失败了，但是显示SUCCEEDED

**Comment by codeBoy777** [comment]
> 你到Yarn的那个日志页面里面看一下有没有报错信息，理论上执行成功以后会把结果数据写回datavines的，如果没有结果的话就有可能是Spark任务执行失败了，但是显示SUCCEEDED
请问一下，这里是填什么环境，linux的吗
![image](https://github.com/datavane/datavines/assets/50009087/63666c15-3fb8-4c3f-b960-29f761e54d0d)
我看有个报错如下：
![image](https://github.com/datavane/datavines/assets/50009087/a1f94d0d-0337-4c1e-91f7-86b3603ddbd3)

**Comment by zixi0825** [comment]
这里面的配置就是填写一些export，确保环境变量可用比如
export SPARK_HOME2=/usr/hdp/2.6.3.0-235/spark-2.4.8-bin-hadoop2.7

**Comment by codeBoy777** [comment]
> 这里面的配置就是填写一些export，确保环境变量可用比如 export SPARK_HOME2=/usr/hdp/2.6.3.0-235/spark-2.4.8-bin-hadoop2.7

我看了下报错的地方
![image](https://github.com/datavane/datavines/assets/50009087/510e26ec-a864-4f80-9e49-5585f2a8973f)
显示密码检查没通过，但是我配置里面填了密码的
{
    "name": "TABLE_ROW_COUNT(#)_task_1689927740119",
    "executePlatformType": "client",
    "executePlatformParameter": {},
    "engineType": "spark",
    "engineParameter": {
        "programType": "JAVA",
        "deployMode": "cluster",
        "driverCores": 1,
        "driverMemory": "512M",
        "numExecutors": 2,
        "executorMemory": "2G",
        "executorCores": 2,
        "others": "--conf spark.yarn.queue=default"
    },
    "parameter": {
        "connectorParameter": {
            "type": "trino",
            "parameters": {
                "database": "hlj_dim",
                "port": "28080",
                "catalog": "hive",
                "host": "172.30.10.91",
                "user": "root"
            }
        },
        "metricParameterList": [
            {
                "metricType": "table_row_count",
                "metricParameter": {
                    "table": "dim_city_info",
                    "metric_database": "hlj_dim"
                },
                "expectedType": "target_table_total_rows",
                "resultFormula": "count",
                "operator": "lt",
                "threshold": 2
            }
        ]
    },
    "errorDataStorageType": "",
    "errorDataStorageParameter": {},
    "validateResultDataStorageType": "mysql",
    "validateResultDataStorageParameter": {
        "password": "123456",
        "driver": "com.mysql.cj.jdbc.Driver",
        "user": "root",
        "url": "jdbc:mysql://172.*****:3306/datavines?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai"
    },
    "retryTimes": 0,
    "retryInterval": 1000,
    "timeout": 3600,
    "timeoutStrategy": "WARN",
    "env": "export SPARK_HOME=/usr/hdp/3.0.0.0-1634/spark2",
    "languageEn": false
}

**Comment by zixi0825** [comment]
创建数据源的时候是有填密码的是吧？那可能是 TrinoConnector 的 bug，我本地都是用的没有密码测试的 ，我处理下

**Comment by codeBoy777** [comment]
> 创建数据源的时候是有填密码的是吧？那可能是 TrinoConnector 的 bug，我本地都是用的没有密码测试的 ，我处理下

我把代码拉下来看了下，你们source和sink都有密码检查，我们trino没有密码的，所以检查没通过

**Comment by codeBoy777** [comment]
> 创建数据源的时候是有填密码的是吧？那可能是 TrinoConnector 的 bug，我本地都是用的没有密码测试的 ，我处理下

你好，这边处理好了吗

**Comment by zixi0825** [comment]
如果你的trino没有密码的话，那应该还不是trino connector的问题，我把spark引擎的password检查都去掉了，你拉一下代码试下

**Comment by codeBoy777** [comment]
> 如果你的trino没有密码的话，那应该还不是trino connector的问题，我把spark引擎的password检查都去掉了，你拉一下代码试下
你这个最新的代码又报了一个SSL的错
<img width="1288" alt="image" src="https://github.com/datavane/datavines/assets/50009087/fa2200fc-a204-4a26-85b5-5c60e8d37be7">

**Comment by codeBoy777** [comment]
> 如果你的trino没有密码的话，那应该还不是trino connector的问题，我把spark引擎的password检查都去掉了，你拉一下代码试下

最近代码运行后报了另一个错
<img width="1306" alt="image" src="https://github.com/datavane/datavines/assets/50009087/4da7bc6d-0676-4d52-a23a-66fbd7b49948">

**Comment by zixi0825** [comment]
> > 如果你的trino没有密码的话，那应该还不是trino connector的问题，我把spark引擎的password检查都去掉了，你拉一下代码试下
> 
> 最近代码运行后报了另一个错 <img alt="image" width="1306" src="https://user-images.githubusercontent.com/50009087/255376069-4da7bc6d-0676-4d52-a23a-66fbd7b49948.png">

这个问题我也是刚发现了，会尽快处理

**Comment by zixi0825** [comment]
> > > 如果你的trino没有密码的话，那应该还不是trino connector的问题，我把spark引擎的password检查都去掉了，你拉一下代码试下
> > 
> > 
> > 最近代码运行后报了另一个错 <img alt="image" width="1306" src="https://user-images.githubusercontent.com/50009087/255376069-4da7bc6d-0676-4d52-a23a-66fbd7b49948.png">
> 
> 这个问题我也是刚发现了，会尽快处理

你试一下把期望值配置为固定值，应该就能运行成功，我调试发现是先连接mysql数据源有密码，再连trino无密码就会报这个错，具体我还需要再调试看看

**Comment by zixi0825** [comment]
抛开这个问题不说，如果用的trino，建议直接用local模式去跑，用spark查询trino不是很好做法

**Comment by zixi0825** [comment]
问题已经解决了，晚点会提交PR处理

**Comment by codeBoy777** [comment]
>

**Comment by codeBoy777** [comment]
> 抛开这个问题不说，如果用的trino，建议直接用local模式去跑，用spark查询trino不是很好做法

好的，trino我试下local。local跟spark我看都走了密码检查的代码，确保两种模式这个ssl的验证是否可以跳过，后面考虑用local的模式

**Comment by zixi0825** [comment]
> > 抛开这个问题不说，如果用的trino，建议直接用local模式去跑，用spark查询trino不是很好做法
> 
> 好的，trino我试下local。local跟spark我看都走了密码检查的代码，确保两种模式这个ssl的验证是否可以跳过，后面考虑用local的模式

local 没有密码检查，spark的密码检查我也去掉了，然后修复了 Authentication using username/password requires SSL to be enabled 这个问题，你可以拉下最新代码试一下

**Comment by codeBoy777** [comment]
> 

![image](https://github.com/datavane/datavines/assets/50009087/70e4b929-1c01-4b88-91b7-f2916e876d32)
lib下有mysql驱动，怎么还是显示找不到呢

**Comment by zixi0825** [comment]
> > 
> 
> ![image](https://user-images.githubusercontent.com/50009087/256463142-70e4b929-1c01-4b88-91b7-f2916e876d32.png) lib下有mysql驱动，怎么还是显示找不到呢

你看下/plugins 目录下有没有驱动

**Comment by codeBoy777** [comment]
> 

有驱动，hive源我测了是没问题的，还是trino有问题
<img width="410" alt="image" src="https://github.com/datavane/datavines/assets/50009087/290c2523-3f69-4e93-bd3c-8e6bcfc4de9c">

**Comment by zixi0825** [comment]
> > 
> 
> 有驱动，hive源我测了是没问题的，还是trino有问题 <img alt="image" width="410" src="https://user-images.githubusercontent.com/50009087/256480389-290c2523-3f69-4e93-bd3c-8e6bcfc4de9c.png">

trino 还有问题？什么问题？
