### ISSUE TITLE
Errors in datavines-postgresql.sql

### ISSUE THREAD

**Issue by KrishnaPG** [datavane/datavines#176]
While running the sql there are few errors encountered as below:

1. Postgres did not like the **backticks** here: https://github.com/datavane/datavines/blob/21d2579d8a90e7ce55132df2cd8f4e276e998be9/scripts/sql/datavines-postgresql.sql#L410-L420

2. Unique constraint is referring to **non-existent column** here:

https://github.com/datavane/datavines/blob/21d2579d8a90e7ce55132df2cd8f4e276e998be9/scripts/sql/datavines-postgresql.sql#L218

3. The **constraint names** are reused and hence **conflicting**. Please make the names unique. Here are few of the duplicates: https://github.com/datavane/datavines/blob/21d2579d8a90e7ce55132df2cd8f4e276e998be9/scripts/sql/datavines-postgresql.sql#L392 and https://github.com/datavane/datavines/blob/21d2579d8a90e7ce55132df2cd8f4e276e998be9/scripts/sql/datavines-postgresql.sql#L405

**Comment by zixi0825** [comment]
postgre sql 暂时不可用，等表结构稳定后再支持

**Comment by zixi0825** [comment]
The problem has been fixed.
