### ISSUE TITLE
[Bug] [作业管理] 在数据质量作业和数据比对作业中的配置文件选项中的json数据可以看到数据源的用户名、密码，有安全漏洞

### ISSUE THREAD

**Issue by taipinglee** [datavane/datavines#185]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datavines-ops/datavines/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

![image](https://github.com/datavane/datavines/assets/20164164/809ee1b0-6a2b-40c9-bbb3-bdbebc554af5)
![image](https://github.com/datavane/datavines/assets/20164164/e9eea54b-f4d8-4cda-8218-e759fe7e65e2)

### DataVines Version

dev

### DataVines Config

```conf
none
```

### Running Command

```shell
local
```

### Error Exception

```log
配置文件json可以直接查看到数据源的用户名、密码，有安全漏洞
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by zixi0825** [comment]
Thank you for your feedback. We will fix it as soon as possible.

**Comment by lixuey** [comment]
I will fix fit,

**Comment by zixi0825** [comment]
The problem has been fixed.
