### ISSUE TITLE
[Bug] [表概览列作业数统计] 列作业数统计统计与实际不符

### ISSUE THREAD

**Issue by taipinglee** [datavane/datavines#186]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datavines-ops/datavines/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

![image](https://github.com/datavane/datavines/assets/20164164/971af91c-c9dc-4700-97c3-012e2e4f9879)
![image](https://github.com/datavane/datavines/assets/20164164/12e2368d-7c0f-4273-a27c-62eb911b4ee6)

### DataVines Version

dev

### DataVines Config

```conf
local
```

### Running Command

```shell
local
```

### Error Exception

```log
实际在dv_catalog_entity_instance表的properties,description,version三个字段上都建有一个作业，但在表概览列作业数统计时，显示为0；应该显示为1，与实际不符。
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by zixi0825** [comment]
Thank you for your feedback. We will fix it as soon as possible.

**Comment by zixi0825** [comment]
The problem has been fixed.
