### ISSUE TITLE
[Bug] [Module Name] Bug 数据对比的时候 数据源 2 配置好之后显示 0，且拿不到列信息

### ISSUE THREAD

**Issue by wanhuhou** [datavane/datavines#195]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datavines-ops/datavines/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

数据对比的时候 数据源 2 配置好之后显示 0，且拿不到列信息，点击运行之后报错
![image](https://github.com/datavane/datavines/assets/35321350/6c040829-0ada-4da9-aa5c-3a873b364e1d)

### DataVines Version

1.0.0-SNAPSHOT

### DataVines Config

```conf
local 模式
```

### Running Command

```shell
数据比对
```

### Error Exception

```log
![image](https://github.com/datavane/datavines/assets/35321350/6c040829-0ada-4da9-aa5c-3a873b364e1d)
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by zixi0825** [comment]
麻烦提供详细点的信息，比如数据源类型，你数据比对的脚本等等

**Comment by zixi0825** [comment]
The problem has been fixed.
