### ISSUE TITLE
[Feature][Module Name] Feature title

### ISSUE THREAD

**Issue by wanhuhou** [datavane/datavines#199]
### Search before asking

- [X] I had searched in the [feature](https://github.com/datavines-ops/datavines/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

建议：
1.配置的任务规则可以 自定义规则作业名称。现在的规则作业名，应该算作规则类型吧
2.任务规则列表，每列显示的数据信息太少，例如配了调度信息可以展示出来，作业状态也可以展示出来
3.实例列表，当前运行的任务信息

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by zixi0825** [comment]
This feature has been completed.
