### ISSUE TITLE
[Feature][Module Name] spark任务Livy提交

### ISSUE THREAD

**Issue by winghv** [datavane/datavines#200]
### Search before asking

- [X] I had searched in the [feature](https://github.com/datavines-ops/datavines/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

目前datavines的spark引擎执行规则检测的任务提交启动是最传统shell形式的提交，期望支持Livy这种更灵活的提交方式

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by zixi0825** [comment]
The feature has been finished.
