### ISSUE TITLE
[Feature][Module Name] 规则校验任务的资源控制

### ISSUE THREAD

**Issue by winghv** [datavane/datavines#201]
### Search before asking

- [X] I had searched in the [feature](https://github.com/datavines-ops/datavines/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

像spark跑规则校验目前大部分是一张表或多张表启动一个spark任务，如果任务数量很多，对于集群资源占用造成影响，可以做一个提交控制已运行的任务数量

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by zixi0825** [comment]
The feature has been finished.
