### ISSUE TITLE
[Feature][Module Name] 数据质量作业查看页面优化 建议

### ISSUE THREAD

**Issue by MYiYang** [datavane/datavines#211]
### Search before asking

- [X] I had searched in the [feature](https://github.com/datavines-ops/datavines/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

数据质量作业查看页面优化 建议

### Usage Scenario

目前的数据质量作业页面确实也可以查看到每个库表的 列 质量执行情况，但是多库表情况下 作业没有进行库表分类，导致查看起来页面有一定的混乱，如果对库表进行分类，详细页面再能看到当前库表的列质量执行情况，这样查阅起来可能会更直观一点

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by zixi0825** [comment]
This feature has been completed
