### ISSUE TITLE
[Feature][connector] Hive connector support HA zookeeper

### ISSUE THREAD

**Issue by winghv** [datavane/datavines#224]
### Search before asking

- [X] I had searched in the [feature](https://github.com/datavines-ops/datavines/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

  
当前仅支持Hive jdbc 单点直连形式，很多生产实际中，需要HA zookeeper 连接形式

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by zixi0825** [comment]
The feature has been finished.
