### ISSUE TITLE
[Feature][Server] Improve JobList Page

### ISSUE THREAD

**Issue by zixi0825** [datavane/datavines#237]
### Search before asking

- [X] I had searched in the [feature](https://github.com/datavines-ops/datavines/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

作业列表增加筛选条件
- 数据库、表、列、创建时间范围

增加展示字段
- 定时调度的cron表达式
- 最近一次执行检查的时间
- 执行成功数、失败数
-------------------------------------------------
Adding Filter Criteria to the Job List
- Database, Table, Column, Creation Time Range

Add display fields
- Cron expression for timed scheduling
- Last time inspection was performed
- Number of successful and failed executions

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by xxzuo** [comment]
I will do it.

**Comment by xxzuo** [comment]
作业列表显示的字段是更新时间，所以我加的是 更新时间筛选项，而不是创建时间筛选项
