### ISSUE TITLE
[Feature][Server] Add a filter input under the column check box list when running the data profile

### ISSUE THREAD

**Issue by zixi0825** [datavane/datavines#240]
### Search before asking

- [X] I had searched in the [feature](https://github.com/datavines-ops/datavines/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

 Add a filter input under the column check box list when running the data profile

——————————————————————————————————————————

运行数据概览时在弹出的列勾选对话框下增加过滤条件输入框

![image](https://github.com/datavane/datavines/assets/10829956/ffda274c-c735-49a8-9790-9dc017a77d48)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by xxzuo** [comment]
i will do it
