### ISSUE TITLE
[Bug] Error Data Storage

### ISSUE THREAD

**Issue by zhugezifang** [datavane/datavines#242]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datavines-ops/datavines/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

错误数据存储，选择的时候，不能选择本地数据源

![image](https://github.com/datavane/datavines/assets/28300167/8f14ce89-b4ac-4f65-a457-db73b09debfb)

### DataVines Version

dev

### DataVines Config

```conf
mysql
```

### Running Command

```shell
local
```

### Error Exception

```log
no
```

### Engine Type

local

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by zixi0825** [comment]
这个不是选择的，而是手动输入，你可以输入你要检查的数据源所在数据库实例里的任意一个库，https://datavane.github.io/datavines-website/docs/features/error-data-storage
