### ISSUE TITLE
[Bug] [Job] 无法修改作业的SLA配置选项

### ISSUE THREAD

**Issue by wzcyc** [datavane/datavines#295]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datavines-ops/datavines/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

有两个问题：
1. job规则的SLA起效后，后续无法更改"SLA配置“”选择其他SLA选项。可以选择和保存，没有起效。再打开，还是原来的选项。
2. 从“”数据目录“”进入，在查看job配置的时候，SLA配置显示为空。

### DataVines Version

lastest

### DataVines Config

```conf
n/a
```

### Running Command

```shell
n/a
```

### Error Exception

```log
no error
```

### Engine Type

local

### Screenshots

![image](https://github.com/datavane/datavines/assets/744073/ce06fb81-b26a-4e6c-b83e-9dd04edfc67e)
![image](https://github.com/datavane/datavines/assets/744073/613fd85e-9dd6-4458-8381-49217a944dac)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by zixi0825** [comment]
这个问题会明天提交PR进行修复

**Comment by zixi0825** [comment]
问题已经修复
