### ISSUE TITLE
[Feature][notification] support dingding

### ISSUE THREAD

**Issue by lueric123** [datavane/datavines#321]
### Search before asking

- [X] I had searched in the [feature](https://github.com/datavines-ops/datavines/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

告警除了支持飞书，邮件，企业微信外，希望支持钉钉

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by zixi0825** [comment]
已经实现
