### ISSUE TITLE
[Bug] [UI] Whitelabel Error Page

### ISSUE THREAD

**Issue by ocean-zhc** [datavane/datavines#343]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datavines-ops/datavines/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

There are no errors in the log, but the front end is a white page

### DataVines Version

1.0.0-SNAPSHOT

### DataVines Config

```conf
no
```

### Running Command

```shell
no
```

### Error Exception

```log
no
```

### Screenshots
<img width="866" alt="image" src="https://github.com/datavane/datavines/assets/46189785/bb3b1e0c-2a57-4f1a-b0be-e09a8f5b67fa">
<img width="1428" alt="image" src="https://github.com/datavane/datavines/assets/46189785/2bb20ccf-5e30-4c1b-9c86-0cad67e38be0">

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by xxzuo** [comment]
maven 打包的时候 有报错吗

**Comment by yinlice** [comment]
> maven 打包的时候 有报错吗

提供一个打包好的版本可以吗.发现很多人都有打包问题
