### ISSUE TITLE
错误数据存储未存储错误数据，而是存储的符合规则的数据

### ISSUE THREAD

**Issue by jnfJNF** [datavane/datavines#346]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datavines-ops/datavines/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

在执行任务后，点击“错误数据”未显示不符合规则的数据，而是显示的符合规则的数据。

### DataVines Version

dev

### DataVines Config

```conf
无
```

### Running Command

```shell
无
```

### Error Exception

```log
无
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by zixi0825** [comment]
错误数据设计就是符合规则的数据，如果你用的是空值检查规则，那么错误数据就是某字段为空的数据，其他规则都是相似的逻辑

**Comment by jnfJNF** [comment]
![image](https://github.com/datavane/datavines/assets/25213350/d4ad01fa-825c-48f0-af3f-f07bdb5a007d)
![image](https://github.com/datavane/datavines/assets/25213350/4394b17a-8051-4292-9883-f3d7a95c93af)
![image](https://github.com/datavane/datavines/assets/25213350/d4eeb128-4893-462c-86da-0b076cb54fd6)
我的理解是存储不符合规则的数据，但是当我点开后显示的是符合规则的数据。比如我想进行空值检查规则，这里显示的应该是为空的数据，但是我点开后显示的是不为空的数据。

**Comment by zixi0825** [comment]
> ![image](https://private-user-images.githubusercontent.com/25213350/300399425-d4ad01fa-825c-48f0-af3f-f07bdb5a007d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1MjEyMDYsIm5iZiI6MTcwNjUyMDkwNiwicGF0aCI6Ii8yNTIxMzM1MC8zMDAzOTk0MjUtZDRhZDAxZmEtODI1Yy00OGYwLWFmM2YtZjA3YmRiNWEwMDdkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI5VDA5MzUwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3ZTdlZDU3Mjc3NWIxYTNmMjk3NWZiMDljNWIxMjY5ODdkZjIwMDVmYWYzODUxYTU0ZDIxNTc5YTVkMWUyY2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QFt6TQJobAcCba_ciJuwosCBToPaPNX8uKxHYemUYQ4) ![image](https://private-user-images.githubusercontent.com/25213350/300400228-4394b17a-8051-4292-9883-f3d7a95c93af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1MjEyMDYsIm5iZiI6MTcwNjUyMDkwNiwicGF0aCI6Ii8yNTIxMzM1MC8zMDA0MDAyMjgtNDM5NGIxN2EtODA1MS00MjkyLTk4ODMtZjNkN2E5NWM5M2FmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI5VDA5MzUwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThlMjVlMmM3MjJiOTQxN2JhZmE5YzY0ZmU3MTc4Yjc4NmU2ZjYzN2RmMTQ5ZDVjZjk2NTNmMTYzODQ4ZWQ4N2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kglUWAXkgxhKfb8SrhxVBUJ30637rVuG0999jlKd9m8) ![image](https://private-user-images.githubusercontent.com/25213350/300400451-d4eeb128-4893-462c-86da-0b076cb54fd6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1MjEyMDYsIm5iZiI6MTcwNjUyMDkwNiwicGF0aCI6Ii8yNTIxMzM1MC8zMDA0MDA0NTEtZDRlZWIxMjgtNDg5My00NjJjLTg2ZGEtMGIwNzZjYjU0ZmQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI5VDA5MzUwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc5MzQ0MjM4OGEwNjE0YmJkNjZlYmZhMjc1MjNiMGIxNGQ1NjE3MjQyZTEyYWMxYjY1NzJmY2ViZThmMjcwYWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WbrR1q_Mptt2RT6KQC-uE_k1-w1CHZUgVMO6TEL_3SE) 我的理解是存储不符合规则的数据，但是当我点开后显示的是符合规则的数据。比如我想进行空值检查规则，这里显示的应该是为空的数据，但是我点开后显示的是不为空的数据。

你的这个规则是做非空检查，非空检查的执行逻辑就是筛选出该字段不为空的数据，计算符合规则的条数，然后根据你的配置做判断，你想做空值判断，那你应该选择空值检查判断
