### ISSUE TITLE
[Feature][datavines-engine] spark从hive获取数据jdbc问题

### ISSUE THREAD

**Issue by 954031894** [datavane/datavines#347]
### Search before asking

- [X] I had searched in the [feature](https://github.com/datavines-ops/datavines/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

我在计算hive中的表时，遇到了一些问题。尝试解决，看到datavines源码时有一些问题。
spark引擎模块的jdbc连接模块datavines-engine-spark-connector-jdbc的io.datavines.engine.spark.jdbc.source.JdbcSource的getData方法。我看到符合enableHiveSupport以及Hive的驱动，就可以直接返回Hive的数据，但是由于我没有找到设置enableHiveSupport的位置，导致返回的是后面的通用的jdbc连接的数据，我想知道这里enableHiveSupport在哪里进行设置

1.源码图示
<img width="1461" alt="image" src="https://github.com/datavane/datavines/assets/54099901/0f87ee96-9f57-4f69-82c4-6fad4bd6f180">
2.spark-submit提交任务给的json有关配置
<img width="575" alt="image" src="https://github.com/datavane/datavines/assets/54099901/e10b4009-9a55-42fb-be1e-c6e9fe775624">
在环境的conf中一直为null，我没有找到找到通过datavines设置这个的方法

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by zixi0825** [comment]
现在暂时不支持spark直接读取hive数据，预计年后上

**Comment by 954031894** [comment]
好的好的

**Comment by zixi0825** [comment]
现在已经支持Spark直接读取hive数据了，hive数据源中的配置【spark.enable.hive.support=true】 就可以
