### ISSUE TITLE
[Bug] [datavines-connector] Hive数据源抓取数据库跨库问题

### ISSUE THREAD

**Issue by 954031894** [datavane/datavines#350]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datavines-ops/datavines/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

通过Web UI添加Hive数据源时，填写某一个数据库后，抓取的是Hive全部表的信息
查看了一下这个问题pr，有相似的问题，但是解决的是sqlserver和pg
Hive Version:2.3.7

### DataVines Version

dev

### DataVines Config

```conf
略
```

### Running Command

```shell
略
```

### Error Exception

```log
略
```

### Java Version

jdk1.8

### Screenshots

这个采集的是hive得dim层数据，结果拉取了全部数据库的信息
<img width="639" alt="iShot_2024-02-01_10 14 03" src="https://github.com/datavane/datavines/assets/54099901/540cfc1d-cc06-4573-af64-9dbb07162339">

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by xxzuo** [comment]
这里 在代码中 hive 没有重写 getMetadataTables方法
```java
   protected ResultSet getMetadataTables(DatabaseMetaData metaData, String catalog, String schema) throws SQLException {
        return metaData.getTables(catalog, schema, null, TABLE_TYPES);
    }
```
所以 相当于 
```java
   protected ResultSet getMetadataTables(DatabaseMetaData metaData, String catalog, String schema) throws SQLException {
        return metaData.getTables('database', null, null, TABLE_TYPES);
    }
```
对hive来说，这样相当于没有指定 database.  所以需要在 hive connector里重写一下

**Comment by 954031894** [comment]
嗯嗯，知道了。我这边试了一下没有问题
