### ISSUE TITLE
[Bug] [datavines-connector-starrocks] starrocks数据源无法获取表信息

### ISSUE THREAD

**Issue by tonyDong-code** [datavane/datavines#359]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datavines-ops/datavines/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

使用 dev 分支代码编译部署后,添加 starrocks 数据源,可以获取到 database 信息,但是无法获取到 table 信息

### DataVines Version

dev 分支

### DataVines Config

```conf
无
```

### Running Command

```shell
无
```

### Error Exception

```log
无
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by tonyDong-code** [comment]
我将 starrocks connector 中 getTables 方法重写,将从 metaData 获取表信息的逻辑,改为从 information_schema 获取表信息.
我再提交代码时,遇到权限拒绝,请问应该如何提交代码
<img width="561" alt="图片" src="https://github.com/datavane/datavines/assets/72612520/900c261a-bf30-44f5-8a38-a3418bb2107d">

**Comment by xxzuo** [comment]
请参考 https://datavane.github.io/datavines-website/community/contribution_guide/contributor

**Comment by tonyDong-code** [comment]
> 请参考 https://datavane.github.io/datavines-website/community/contribution_guide/contributor

谢谢,已提交 pr

**Comment by zixi0825** [comment]
你的StarRocks版本是多少，我这边是可以正常获取表列表的

**Comment by tonyDong-code** [comment]
3.2.2版本

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年02月20日 19:21 |
| 收件人 | datavane/datavines ***@***.***> |
| 抄送人 | tonyDong-code ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [datavane/datavines] [Bug] [datavines-connector-starrocks] starrocks数据源无法获取表信息 (Issue #359) |

你的StarRocks版本是多少，我这边是可以正常获取表列表的

**Comment by zixi0825** [comment]
This issue has been fixed.
