### ISSUE TITLE
[Feature][数据质量] 数据质量任务支持restapi调用

### ISSUE THREAD

**Issue by lordk911** [datavane/datavines#394]
### Search before asking

- [X] I had searched in the [feature](https://github.com/datavines-ops/datavines/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

定义的数据质量任务，支持通过restapi的方式触发，这样类似于dolphinscheduler的工作流引擎更容易集成

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by zixi0825** [comment]
现在已经支持通过restapi提交任务，可以通过/api/v1/job/execution/submit/data-quality来提交数据质量检查作业
