### ISSUE TITLE
[Bug] [datavines-engine-spark-config]SparkDataProfileMetricBuilder创建的Config在Spark引擎上跑出的actual_value结果值是actual_value_d2b44c38er而不是具体的值

### ISSUE THREAD

**Issue by SkyerYao** [datavane/datavines#412]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datavines-ops/datavines/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

在表列表中执行数据概览任务，使用Spark引擎执行完后没有跑出预期结果，使用Local引擎执行完后能跑出正常结果。

### DataVines Version

1.0

### DataVines Config

```conf
1.0
```

### Running Command

```shell
使用spark引擎运行数据概览任务
```

### Error Exception

```log
写入到数据库表的实际值不正确
```

### Engine Type

Spark3.1.1

### Screenshots

![1380248869](https://github.com/datavane/datavines/assets/27400637/ab1d2c0e-7475-497d-a509-408174c64163)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by zixi0825** [comment]
This issue has been fixed.
