### ISSUE TITLE
[Bug] [Metrics] The Upper case word 'AS' would cause custome_aggregate_sql metric rule failed

### ISSUE THREAD

**Issue by leeoo** [datavane/datavines#436]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datavines-ops/datavines/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

在数据质量自定义SQL规则作业这里，如果自定义的聚合SQL的 as actual_value 部分的 as 大写了，就会报错“... contains placeholder”用小写 as 就正常。
![62867d53fa07ea1f5ee31a39b9172a0](https://github.com/user-attachments/assets/ab9a18b8-6c9c-4c02-b9d1-cc1f53389ce0)
![4900c296f307b7d1072261f4404e7f8](https://github.com/user-attachments/assets/c1fae967-802a-4339-8466-fcbfee0126f1)

### DataVines Version

branch: dev
version: 1.0.0-SNAPSHOT

### DataVines Config

```conf
See detail in 'what happend'.
```

### Running Command

```shell
See detail in 'what happend'.
```

### Error Exception

```log
See detail in 'what happend'.
```

### Engine Type

local

### Java Version

11

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by zixi0825** [comment]
This issue has been fixed in #440
