### ISSUE TITLE
[Bug] [作业] 正则表达式类型的作业，执行引擎选择spark，执行后没有任何结果

### ISSUE THREAD

**Issue by zhaoyunlai** [datavane/datavines#469]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datavines-ops/datavines/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

创建作业时，规则类型选择正则表达式，执行引擎使用spark，作业可以执行成功，但是没有任何结果，其他规则类型的就有结果。

是否因为检查过程中生成的sql语句使用了regexp操作符，而spark sql不支持。
我重新创建自定义聚合SQL规则类型的作业，使用spark支持的正则函数，作业即可执行得到结果。
`select count(1) as actual_value from ${table} where regexp_like(user_name, '^.{1,10}$')`

### DataVines Version

1

### DataVines Config

```conf
无
```

### Running Command

```shell
在页面直接执行作业
```

### Error Exception

```log
无报错
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by zixi0825** [comment]
先去yarn上面看一下任务的执行日志
